name: workflow_test1
on: 
  push:
    branches: [master]
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check repository
      uses: actions/checkout@v2
      
    - name: build and test
      run: |
        apt install libsdl2-dev libsdl2-2.0-0 -y
        cmake CMakeLists.txt
        make
        ./Release/sobel
